# Generated by Django 5.1.3 on 2024-11-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_a', models.CharField(default='Always', max_length=100)),
                ('answer_b', models.CharField(default='Often', max_length=100)),
                ('answer_c', models.CharField(default='Sometimes', max_length=100)),
                ('answer_d', models.CharField(default='Never', max_length=100)),
                ('score_a', models.IntegerField(default=10)),
                ('score_b', models.IntegerField(default=7)),
                ('score_c', models.IntegerField(default=4)),
                ('score_d', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
